### ISSUE TITLE
RobotContainer - there can only be one

### ISSUE THREAD

**Issue by mattdailis** [frc8243/Swerve-Practice-2023#1]
Looks like there are two places that call `new RobotContainer()`. Which is the right one?

https://github.com/frc8243/Swerve-Practice-2023/blob/55a379ab61dc4e3226e621fc6547ca1d7a56c0b7/src/main/java/frc/robot/RobotContainer.java#L17

https://github.com/frc8243/Swerve-Practice-2023/blob/55a379ab61dc4e3226e621fc6547ca1d7a56c0b7/src/main/java/frc/robot/Robot.java#L18

![image](https://github.com/frc8243/Swerve-Practice-2023/assets/1189602/076c0314-2686-48e2-b508-2f25ffb095c2)

**Comment by JulienM14** [comment]
Found the issue! Due to the way code was haphazardly written, it was forgotten to create a way for robot.java to use the RobotContainer created in robotcontainer.java. This was solved by adding a `getInstance()` method to robotcontainer.java, and using that to create the robotcontainer in robot.java

https://github.com/frc8243/Swerve-Practice-2023/blob/142b762a985e6c87002c8e5a4c931194bbd180a2/src/main/java/frc/robot/RobotContainer.java#L57-L59

https://github.com/frc8243/Swerve-Practice-2023/blob/142b762a985e6c87002c8e5a4c931194bbd180a2/src/main/java/frc/robot/Robot.java#L19
